# Generated by Django 4.1.7 on 2026-01-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_App', '0007_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('Doctor_Id', 'Slot', 'Date')},
        ),
    ]
